### ISSUE TITLE
gekaufte Spielfigur auf belegtes Spielfeld platzieren

### ISSUE THREAD

**Issue by ntnptzld** [Lollipop2403/CompGD#1]
man kann gekaufte Spielfiguren auf Felder setzen, wo bereits eine Figur steht.
Die gekaufte Figur wird dann "gelöscht", bzw. nicht gespawnt - sie wird allerdings gecountet und das Geld ebenfalls abgezogen.
Statt dem Spawnen der Spielfigur wird die Spielfigur, die bereits auf dem Feld stand ausgewählt und kann innerhalb der Deathzone bewegt werden.

(Maybe wird die dort stehende Spielfigur auch durch die neu gesetzt Spielfigur überschrieben und die alte Spielfigur wird "gelöscht", bzw. despawnt)

**Comment by Lollipop2403** [comment]
Ich denke ich habe das gefixed. bin mir aber auch nicht 100% sicher was genau du meinst
